# Generated by Django 4.2.4 on 2023-12-14 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numer_IC', models.IntegerField(unique=True)),
                ('Nazwa', models.CharField(default='', max_length=20)),
                ('Rynek', models.CharField(default='', max_length=20)),
                ('Opis', models.CharField(default='', max_length=40)),
                ('Rejestracja', models.DateField(default=django.utils.timezone.now)),
                ('Data_rysunki', models.DateField(default=django.utils.timezone.now)),
                ('Data_części', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('DRAWINGS CONFIRMATION', 'DRAWINGS CONFIRMATION'), ('DELIVERY CONFIRMATION', 'DELIVERY CONFIRMATION'), ('OTHER', 'OTHER')], max_length=50, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('TO DO', 'TO DO'), ('COMPLETED', 'COMPLETED'), ('IN-PROGRESS', 'IN-PROGRESS')], default='TO DO', max_length=50, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='komunikator.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='komunikator.task')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
