# Generated by Django 4.2.4 on 2023-12-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komunikator', '0002_alter_comment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
