# Generated by Django 4.2.4 on 2024-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komunikator', '0004_parametr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametr',
            name='parametr',
            field=models.IntegerField(),
        ),
    ]
