# Generated by Django 4.2.4 on 2024-02-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komunikator', '0005_alter_parametr_parametr'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='confirmation_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
